#driver=com.mysql.cj.jdbc.Driver
#driver=org.h2.Driver
#driver=org.postgresql.Driver
driver=org.mariadb.jdbc.Driver

#url=jdbc:mysql://localhost:3306/drawing_db?createDatabaseIfNotExist=true
#url=jdbc:h2:~/drawing_db
#url=jdbc:postgresql://localhost:5432/drawing_db
url=jdbc:mariadb://localhost:3306/drawing_db?createDatabaseIfNotExist=true

username=root
password=root
#password=