#driver JDBC , necessite mysql-connector-...jar ou autre dans le CLASSPATH
#driver=com.mysql.cj.jdbc.Driver
#driver=org.h2.Driver
#driver=org.postgresql.Driver
driver=org.mariadb.jdbc.Driver
#url de la base de donnée
url=jdbc:mariadb://localhost:3306/person_db
username=root
password=root